### ISSUE TITLE
如何运行项目

### ISSUE THREAD

**Issue by sucof** [godcong/fate#1]
请问有文档吗，该如何运行该项目？
@godcong

**Comment by godcong** [comment]
更新下版本,刚更新了下加了字的五行过滤

可以使用下面的接口:
fate.FilterBest(fate.NewName("毛"), "水", "金")
第一个输入姓,第二,第三分别对应第二字和第三字的五行属性(喜用神需要)
然后会输出
姓名的三才五格[天才:土,人才:土,地才:金] 
三才五格差的都会过滤掉.
然后是对应字的笔画和拼音,写法
输出结果类似下面:
=== RUN   TestFilterBest
2018/06/06 23:05:33 [天才:土,人才:土,地才:火]
2018/06/06 23:05:33 [天才:土,人才:土,地才:金]
2018/06/06 23:05:33 [天才:土,人才:土,地才:火]
2018/06/06 23:05:33 [天才:土,人才:土,地才:金]
第二字： 2
乜miē,niè,八bā,勹bāo,
第三字： 5
市shì,申shēn,且jū,qiě,世shì,史shǐ,司sī,叱chì,失shī,四sì,正zhèng,zhēng,玊sù,主zhù,zhǔ,斥chì,仞rèn,仕shì,仟qiān,仙xiān,示shì,生shēng,矢shǐ,乏fá,乍zhà,出chū,凸tū,卮zhī,石dàn,shí,尻kāo,占zhàn,zhān,刊kān,
2018/06/06 23:05:33 [天才:土,人才:土,地才:火]
2018/06/06 23:05:33 [天才:土,人才:金,地才:金]

然后,挑选自己喜欢的字就可以了.

使用事前记得先导入mysql库, 用到的库文件都在sql下面
