### ISSUE TITLE
AI取名的一些想法

### ISSUE THREAD

**Issue by wongoo** [godcong/fate#11]
之前调研过取名的工具，一直没发现这个。后来发现百度有取名工具，可以直接url访问，就自己开发了一个小工具 https://github.com/wongoo/namer。

同时发现很多取名的平台的算法不尽相同， 取名打分也完全不一样，要搞清楚其中的算法也很是一件很麻烦的事情。能够把算法引入的确厉害！ 你的AI计算这个想法不错， 可以汇集大量文集，计算大量人名，计算名气得分。 但我取名有一个前提，就是用的人少，且有一定意义。比如我给我儿子取名 `寻意`。 AI计算看能不能也考虑往这个方向上去设计，相信大家会更喜欢。

**Comment by godcong** [comment]
取名字规则算法，从古至今，门派算法就那几种啊。
就是整理计算起来很麻烦啊。
没有你说的算法不尽相同啊。。。

网上许多的我也查过，不规范乱弄的好多。
究其原因大致：1. 数据不足或没有数据 2.不知道详细算法 3. 自己定义的规则

**Comment by godcong** [comment]
no more questions
