### ISSUE TITLE
请问，现在有可以使用的版本么？孩子下个月要出生了准备使用下这个项目😄

### ISSUE THREAD

**Issue by peirancao** [godcong/fate#15]

**Comment by godcong** [comment]
最新版，这两天我会放上字库和使用方法，字库的字还有些问题，选完以后，可以去起名一些网站验证下。
如果急着用的话可以使用第二版。

**Comment by peirancao** [comment]
@godcong 好的 过两天试用下最新版吧我这不是很急😊，非常感谢🙏。

**Comment by godcong** [comment]
https://github.com/godcong/fate/releases/tag/v3.0.0
