### ISSUE TITLE
关于喜用神的请教

### ISSUE THREAD

**Issue by bebestmaple** [godcong/fate#16]
请问喜用神不是分为喜神和用神吗？请问这个只出来一个是喜神还是用神？

**Comment by godcong** [comment]
> 请问喜用神不是分为喜神和用神吗？请问这个只出来一个是喜神还是用神？
这个不是喜神、用神，忌神、仇神，闲神的算法.

ーーーーーーーーーーーーー
这是平衡用神, 讲究的是五行间平衡,互补. 
自古以来就有过盈则亏的说法,
这个算法算是比较平稳的.
如果用上面的算法的话,可能有两种情况发生.
极好与极坏两种极端我觉得都不可取.
所谓过刚易折,极好也有可能变成极坏.
所以经过多次测算后用了平衡用神的算法来实现.

**Comment by bebestmaple** [comment]
请问平衡用神用在起名的哪里？哪里有看到喜神、用神，忌神、仇神，闲神的算法吗？对这个比较感兴趣

**Comment by godcong** [comment]
和平衡用神差不多。。。
你算出来用神就能推出喜，忌，仇，闲了

**Comment by bebestmaple** [comment]
就是想请教下这个 喜神、用神，忌神、仇神，闲神是怎么算的，因为一直找不到相关的资料，自己看周易的相关理论又有点看不太明白

**Comment by godcong** [comment]
not fate questions
