### ISSUE TITLE
小白运行教程

### ISSUE THREAD

**Issue by ZmjDns** [godcong/fate#17]
本人GO小白想给宝宝取名，但是不会运行，希望大佬提供一下运行教程

**Comment by godcong** [comment]
今晚或明天,我会放一个cmd的版本和数据.
但是数据是mysql的还是需要你自己导入

**Comment by ZmjDns** [comment]
那真是太好了，导入数据是没有问题的，希望大佬能把供数据出来，万分感谢

**Comment by godcong** [comment]
https://github.com/godcong/fate/releases/tag/v3.0.0
