### ISSUE TITLE
运行后报错，帮忙看下吧。。

### ISSUE THREAD

**Issue by peirancao** [godcong/fate#18]
database: 
born: 
last 
[xorm] [info]  2019/11/26 09:47:55.875861 [SQL] SELECT `TABLE_NAME`, `ENGINE`, `TABLE_ROWS`, `AUTO_INCREMENT`, `TABLE_COMMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB' OR `ENGINE` = 'TokuDB') [fate]
[xorm] [info]  2019/11/26 09:47:55.879872 [SQL] SELECT `COLUMN_NAME`, `IS_NULLABLE`, `COLUMN_DEFAULT`, `COLUMN_TYPE`, `COLUMN_KEY`, `EXTRA`,`COLUMN_COMMENT` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? [fate wu_ge_lucky]
[xorm] [info]  2019/11/26 09:47:55.882700 [SQL] SELECT `INDEX_NAME`, `NON_UNIQUE`, `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`STATISTICS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? [fate wu_ge_lucky]
[xorm] [info]  2019/11/26 09:47:56.416185 [SQL] SELECT count(*) FROM `wu_ge_lucky` - took: 530.299437ms
panic: runtime error: index out of range [0] with length 0

goroutine 35 [running]:
github.com/godcong/fate.filterWuGe(0xc0002b60c0, 0xc00022e3c0, 0x0, 0x0)
        /Users/peirancao/Projects/fate/wuge.go:241 +0x4ae
github.com/godcong/fate.(*fateImpl).getWugeName.func2(0xc0002b60c0, 0xc00022e3c0, 0xc000298270)
        /Users/peirancao/Projects/fate/fate.go:233 +0x39
created by github.com/godcong/fate.(*fateImpl).getWugeName
        /Users/peirancao/Projects/fate/fate.go:232 +0xf3
exit status 2

**Comment by godcong** [comment]
姓没有输入
NewFate()第一个参数就是姓,第二个参数是生日

**Comment by peirancao** [comment]
嗯嗯 现在一直输出这些,是不是正在算啊 😄 `traditional_total_stroke`, `name_science`, `wu_xing`, `lucky`, `regular`, `traditional_character`, `variant_character`, `comment` FROM `character` WHERE (pin_yin IS NOT NULL) AND (stroke=? OR kang_xi_stroke=? OR simple_total_stroke=? OR traditional_total_stroke=?) []interface {}{11, 11, 11, 11} - took: 4.434817ms
[xorm] [info]  2019/11/26 16:53:17.521872 [SQL] SELECT `hash`, `pin_yin`, `ch`, `radical`, `radical_stroke`, `stroke`, `is_kang_xi`, `kang_xi`, `kang_xi_stroke`, `simple_radical`, `simple_radical_stroke`, `simple_total_stroke`, `traditional_radical`, `traditional_radical_stroke`, `traditional_total_stroke`, `name_science`, `wu_xing`, `lucky`, `regular`, `traditional_character`, `variant_character`, `comment` FROM `character` WHERE (pin_yin IS NOT NULL) AND (stroke=? OR kang_xi_stroke=? OR simple_total_stroke=? OR traditional_total_stroke=?) []interface {}{12, 12, 12, 12} - took: 2.664603ms
[xorm] [info]  2019/11/26 16:54:41.666239 [SQL] SELECT `hash`, `pin_yin`, `ch`, `radical`, `radical_stroke`, `stroke`, `is_kang_xi`, `kang_xi`, `kang_xi_stroke`, `simple_radical`, `simple_radical_stroke`, `simple_total_stroke`, `traditional_radical`, `traditional_radical_stroke`, `traditional_total_stroke`, `name_science`, `wu_xing`, `lucky`, `regular`, `traditional_character`, `variant_character`, `comment` FROM `character` WHERE (pin_yin IS NOT NULL) AND (stroke=? OR kang_xi_stroke=? OR simple_total_stroke=? OR traditional_total_stroke=?) []interface {}{11, 11, 11, 11} - took: 12.220091ms
[xorm] [info]  2019/11/26 16:54:41.773548 [SQL] SELECT `hash`, `pin_yin`, `ch`, `radical`, `radical_stroke`, `stroke`, `is_kang_xi`, `kang_xi`, `kang_xi_stroke`, `simple_radical`, `simple_radical_stroke`, `simple_total_stroke`, `traditional_radical`, `traditional_radical_stroke`, `traditional_total_stroke`, `name_science`, `wu_xing`, `lucky`, `regular`, `traditional_character`, `variant_character`, `comment` FROM `character` WHERE (pin_yin IS NOT NULL) AND (stroke=? OR kang_xi_stroke=? OR simple_total_stroke=? OR traditional_total_stroke=?) []interface {}{14, 14, 14, 14} - took: 3.256323ms

**Comment by godcong** [comment]
嗯,你看运行目录下那个zap.log的输出就行了

**Comment by peirancao** [comment]
好了可以看到结果了😄 请问 可以筛选出高分的名字么？我测试了几个 分数都不高。。

**Comment by peirancao** [comment]
我这没找到zap.log 但是在fate.log里面有记录看着

**Comment by godcong** [comment]
对,就是fate.log
项目太多有点搞混了...


要分数高的话,开启全局变量会严格过滤五格:
```
fate.HardMode = true
```

这个我觉得没什么必要,五格中总格是吉就可以了

还有这几个边旁的字笔画算法不大一样
"扌",	"忄",	"氵",	"犭",	"礻",	"王",	"艹","衤",	"月",	"辶"
这两天在写修正笔画的算法.
