### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by songjian0270** [godcong/fate#19]
go build 的时候需要sqlite3吗？

**Comment by godcong** [comment]
因为库是支持mysql和sqlite3的所有,编译的时候两个包都要用到.
可以直接使用go mod tidy下载更新所有的包

**Comment by songjian0270** [comment]
已经下载 go build的时候还是不行的呢
go build github.com/mattn/go-sqlite3: D:\Program Files\Go\pkg\tool\windows_amd64\cgo.exe: exit status 2

**Comment by godcong** [comment]
你没有安装c编译库...
我晚点去掉sqlite3再发一个版本吧...

**Comment by songjian0270** [comment]
安装了,好像是mingw的版本32的系统是64的

**Comment by godcong** [comment]
我记得我用的好像是这个:
http://sourceforge.net/projects/mingw-w64/files/Toolchains%20targetting%20Win32/Personal%20Builds/mingw-builds/installer/mingw-w64-install.exe/download

**Comment by songjian0270** [comment]
在线的下不了  只能下载离线的了

**Comment by songjian0270** [comment]
大佬數據庫 必須在本地嗎？

**Comment by songjian0270** [comment]
已经解决
