### ISSUE TITLE
运行错误

### ISSUE THREAD

**Issue by songjian0270** [godcong/fate#20]
SELECT `TABLE_NAME`, `ENGINE`, `TABLE_ROWS`, `AUTO_INCREMENT`, `TABLE_COMMENT` from `INFORMATION_SCHEMA`.`TABLES` WHERE `TABLE_SCHEMA`=? AND (`ENGINE`='MyISAM' OR `ENGINE` = 'InnoDB' OR `ENGINE` = 'TokuDB') [fate]
[xorm] [info]  2019/12/09 18:48:10.741237 [SQL] SELECT `COLUMN_NAME`, `IS_NULLABLE`, `COLUMN_DEFAULT`, `COLUMN_TYPE`, `COLUMN_KEY`, `EXTRA`,`COLUMN_COMMENT` FROM `INFORMATION_SCHEMA`.`COLUMNS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? [fate wu_ge_lucky]
[xorm] [info]  2019/12/09 18:48:10.770473 [SQL] SELECT `INDEX_NAME`, `NON_UNIQUE`, `COLUMN_NAME` FROM `INFORMATION_SCHEMA`.`STATISTICS` WHERE `TABLE_SCHEMA` = ? AND `TABLE_NAME` = ? [fate wu_ge_lucky]
[xorm] [info]  2019/12/09 18:48:11.125181 [SQL] SELECT count(*) FROM `wu_ge_lucky` - took: 328.008ms
panic: runtime error: index out of range [0] with length 0

goroutine 22 [running]:
github.com/godcong/fate.filterWuGe(0xc00025b7a0, 0xc000258180, 0x0, 0x0)
        D:/MyGo/fate-3.0.0/wuge.go:241 +0x4b5
github.com/godcong/fate.(*fateImpl).getWugeName.func2(0xc00025b7a0, 0xc000258180, 0xc000229060)
        D:/MyGo/fate-3.0.0/fate.go:233 +0x40
created by github.com/godcong/fate.(*fateImpl).getWugeName
        D:/MyGo/fate-3.0.0/fate.go:232 +0xfa
exit status 2

**Comment by songjian0270** [comment]
.data结尾的数据需要导入吗？还是只需要导入mysql 的

**Comment by songjian0270** [comment]
是没输入对于参数@！。@

**Comment by godcong** [comment]
嗯，是少了参数。。。
有点影响体验，我加了check

**Comment by songjian0270** [comment]
enen，早点休息，这么晚了

**Comment by songjian0270** [comment]
大佬，这个数据是哪里搞得哦一个个录入的吗

**Comment by godcong** [comment]
一部分excavator抓的,手动改了一部分
