### ISSUE TITLE
golang学习

### ISSUE THREAD

**Issue by songjian0270** [godcong/fate#24]
func GetTermInfo(y, n int) int {
	y = fixSuffix(y)
	if y < 0 || y > len(termInfoList) {
		return -1
	}
	if n < 1 || n > 24 {
		return -1
	}
	i := (n - 1) / 4 * 5
	n = (n - 1) % 4
	idx, _ := strconv.ParseInt(termInfoList[y][i:i+5], 16, 64)
	a := strconv.FormatInt(idx, 10)
	day := []string{a[0:1], a[1:3], a[3:4], a[4:6]}
	i, _ = strconv.Atoi(day[n])
	return i
}

不知道idx, _ := strconv.ParseInt(termInfoList[y][i:i+5], 16, 64)是什么意思的呢  termInfoList是切片的概念吗，大神

**Comment by songjian0270** [comment]
zdao le .

**Comment by godcong** [comment]
termInfoList[y][i:i+5] 取i到i+5位,16进制数
然后ParseInt转成int

**Comment by songjian0270** [comment]
enen
