### ISSUE TITLE
这要是普及了，大家取出来的名字不都一样哈？

### ISSUE THREAD

**Issue by hawk86104** [godcong/fate#29]
请问 这重复性，怎么解决哈

**Comment by godcong** [comment]
按照八字不同，名字都会有区别的，怎么会一样？

**Comment by iyh** [comment]
好多ga网站上有能查重名人数的，自己查查咯
（只举例）
http://www.gov.cn/fuwu/bmfw/jstmcx/index.html
http://www.wjw.jsga.gov.cn/cname/index

**Comment by godcong** [comment]
感谢@iyh
按照生成规则测试了一些,重复率极低(我选几个大部分重复率为0）
