### ISSUE TITLE
运行问题

### ISSUE THREAD

**Issue by sucof** [godcong/fate#3]
按照大大你的建议，第三方依赖库都用release版本，已经没有问题，但是使用如下的代码还是不行，刚接触go，问题有点初级啊，别见怪
```
package main
import (
	"fmt"
	"strings"
	"github.com/godcong/fate"
	"github.com/godcong/fate/model"
	"testing"
)

func main() {
	fmt.Println("hello world . 你好 世界！")
	fate.FilterBest(fate.NewName("毛"), "水", "金")
}
```

我看着name.go中，有newName的定义，但是感觉参数不对，是这种写法吗？

**Comment by godcong** [comment]
是这样写的

**Comment by sucof** [comment]
但是运行还是有问题，我用的是go run main，错误如下：
./main.go:12: undefined: fate.NewName
main在cmd/console下

**Comment by godcong** [comment]
@sucof 你使用v2版本试试,master是v3版本.正在修改,还没写好

**Comment by godcong** [comment]
no more questions
