### ISSUE TITLE
可视化网页端客户端

### ISSUE THREAD

**Issue by bugmakesprogress** [godcong/fate#31]
对于fate项目的可观测性或者使用价值情况评估会有些提升~ 
如果觉得不急我也可以帮忙弄下 就是需要一定时间再复习复习前端

**Comment by godcong** [comment]
暂时接口还没稳定，准备添加rpc输出

**Comment by godcong** [comment]
这个版本添加了二进制文件生成姓名。

**Comment by design365** [comment]
没必要可视化，能解决结果出来的姓名不那么偏僻字就行了 ，现在出来的很多都是偏僻字，明显看着就不太好。

**Comment by wakaryry** [comment]
差不多的话，我可以弄各个端小程序，包括app

**Comment by godcong** [comment]
@wakaryry 是一直有这个想法，但是一直没有时间去弄。

**Comment by wakaryry** [comment]
> @wakaryry 是一直有这个想法，但是一直没有时间去弄。

只要有接口能提供就行。可以对一下能够提供什么数据。我可以出设计+前台代码

**Comment by godcong** [comment]
> > @wakaryry 是一直有这个想法，但是一直没有时间去弄。
> 
> 只要有接口能提供就行。可以对一下能够提供什么数据。我可以出设计+前台代码。
> 
> 我也可以先出一个设计看看

主要是效率问题还没解决, 运算一批名字需要的时间有点久.这样的对服务器压力有点大.

**Comment by wakaryry** [comment]
@godcong 俺也不知道。俺也不敢问。是不是有些评测是与时间无关的，这样其实可以自动先生成很多的名字+描述数据存库里

**Comment by godcong** [comment]
> @godcong 俺也不知道。俺也不敢问。是不是有些评测是与时间无关的，这样其实可以自动先生成很多的名字+描述数据存库里

现在根据统计单姓3484个，复姓52612032个
假设一个人姓的数据单姓维度是1、双姓的维度是2*3484
那就有3484＋2*3484+52612032
那他这一年的八字维度是60*60*60
那所有姓名一年的数据就有11,366,456,544,000种情况
如果是所有甲子的话那得有681,987,392,640,000种情况
这个生成过程我感觉会非常久...数据量也太过庞大了...

**Comment by wakaryry** [comment]
很吓人的数据量。那就基本上提供几种方式：

- 给用户做简单的常用名字输出，用户固定姓或者姓+某些固定字；
- 用户指定的某个名字做详细测评；

先是给建议性的，这些名字只是符合一些简单的规范；

然后是专业性的，这些需要用户自己来指定；

不知道给一个名字+时间出详细的报告要多久。

**Comment by godcong** [comment]
> 很吓人的数据量。那就基本上提供几种方式：
> 
> * 给用户做简单的常用名字输出，用户固定姓或者姓+某些固定字；
> * 用户指定的某个名字做详细测评；
> 
> 先是给建议性的，这些名字只是符合一些简单的规范；
> 
> 然后是专业性的，这些需要用户自己来指定；
> 
> 不知道给一个名字+时间出详细的报告要多久。

报告是已经有结果了,显示结果的详细信息而已.一般对应的都是固定性的.

**Comment by godcong** [comment]
add requirements into #21
