### ISSUE TITLE
{"msg":"Error 1054: Unknown column 'zong_sex' in 'field list'"}

### ISSUE THREAD

**Issue by reechou** [godcong/fate#32]
最新的代码出现错误

建议作者：
master分支最好是稳定的代码
自己开发的话，开一个dev分支吧

**Comment by godcong** [comment]
和代码没关系
表字段没更新，重新sync下WuGeLucky这个表
数据在重新生成，到时候可以直接导入，估计还要几天

**Comment by godcong** [comment]
更新下字库吧，
最新的字库已经和最新版本一起release了:
https://github.com/godcong/fate/releases/download/v3.1.1/fate0206.7z
