### ISSUE TITLE
为什么不用sqlite等嵌入式数据库

### ISSUE THREAD

**Issue by zjfsdnu** [godcong/fate#34]
还得专门装个mysql 有点麻烦啊！

**Comment by godcong** [comment]
原来有的，但是并发上，还有编译上有点问题就去掉了（要用到CGO，部分使用者不熟悉编译会报错）

**Comment by zjfsdnu** [comment]
个人使用 没太有必要用并发吧

**Comment by godcong** [comment]
你非要用sqlite的话也是可以的,用的是xorm,你把database驱动换成sqlite就行了
但这需要你自己编译。
你还要把数据库导入到sqlite里去.

mysql只是我写的一个实现.
