### ISSUE TITLE
config.json数据库连接已经修改，还是错误，

### ISSUE THREAD

**Issue by luyuwww** [godcong/fate#35]
config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:localhost Port:3306 User:root Pwd:root1234 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1581225099.605244,"caller":"fate/fate.go:133","msg":"正在使用Fate 生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1581225099.6062613,"caller":"console/name.go:34","msg":"makename","error":"count total error:The system cannot find the path specified.","stacktrace":"github.com/goextension/log.Fatalw\n\tD:/workspace/golang/path/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/workspace/golang/project/fate/cmd/console/name.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/workspace/golang/project/fate/cmd/console/main.go:21\nruntime.main\n\tD:/workspace/golang/go_base/go1.13.1/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
log显示数据库错误：
{"level":"fatal","ts":1581225099.6062613,"caller":"console/name.go:34","msg":"makename","error":"count total error:The system cannot find the path specified."
确认下：
1. 数据库导入了吗？
2.连接是否正确
3. 下面这几个参数是否正确
Host:localhost Port:3306 User:root Pwd:root1234 Name:fate
