### ISSUE TITLE
其实可以加上是否有辈分用字可是否常用字的选项

### ISSUE THREAD

**Issue by crystalsis** [godcong/fate#36]
起名的时候这两项也算是考虑的点，有的人会在名字里加辈分字有的不加，辈分字还有加在中间和加在后面两种。有的人会考虑某些地方输入GB2312以外的字不方便，有的人不考虑。

**Comment by godcong** [comment]
辈分用字在计划中。
https://github.com/godcong/fate/issues/21

常用字库一直在升级。
