### ISSUE TITLE
the system cannot find the path specified[win]

### ISSUE THREAD

**Issue by westfly** [godcong/fate#39]
根据文章的描述[windows server上 gorm 连接DB提示 the system cannot find the path specified](https://studygolang.com/articles/22849)应该是gorm 找不到 zoneinfo.zip。

[time: LoadLocation doesn't work on windows if Go is not installed](https://github.com/golang/go/issues/21881)

这个issue，建议将其打包在exe中
https://github.com/holochain/org/issues/46

**Comment by godcong** [comment]
fixed https://github.com/godcong/fate/commit/c969dba1f6ce33b555adeee059e2e5446828abb1
