### ISSUE TITLE
怎么把这个项目运行起来。

### ISSUE THREAD

**Issue by awebc** [godcong/fate#4]
不知道是否有时间写一下go项目运行配置大概的流程。原来是写php的，对go不熟悉，看了网上go的教程环境配置等，还是不行。

**Comment by godcong** [comment]
用vgo获取项目:
vgo get github.com/godcong/fate@2.0.1
或者自己clone到本地，check out 【v2】这个branch

并按照v2的readme流程来操作。
你先试下。

**Comment by wakaryry** [comment]
这个写完了吗？想逆天改命一下。

**Comment by godcong** [comment]
v3版本预计在这两月完成初版

**Comment by wisfern** [comment]
go/src/github.com/godcong/fate/charset.go:654:10: undefined: excavator.Get
go/src/github.com/godcong/fate/charset.go:720:2: undefined: excavator.UpdateKangXi
go/src/github.com/godcong/fate/charset.go:720:63: undefined: excavator.CharDetail

总是遇到 这个问题，我看GOPATH里面其实是有这个库的。

**Comment by wisfern** [comment]
还有这个，我用的版本是v2
gopkg/src/github.com/godcong/fate/model/base.go:38:19: multiple-value uuid.NewV1() in single-value context

**Comment by godcong** [comment]
> 还有这个，我用的版本是v2
> gopkg/src/github.com/godcong/fate/model/base.go:38:19: multiple-value uuid.NewV1() in single-value context

这是使用uuid的master库的原因。用它最新的release库就行了。

**Comment by godcong** [comment]
> go/src/github.com/godcong/fate/charset.go:654:10: undefined: excavator.Get
> go/src/github.com/godcong/fate/charset.go:720:2: undefined: excavator.UpdateKangXi
> go/src/github.com/godcong/fate/charset.go:720:63: undefined: excavator.CharDetail
> 
> 总是遇到 这个问题，我看GOPATH里面其实是有这个库的。

这部分是原来抓数据的用的，直接使用数据库的话是不需要这块的。我加个fix，注释掉吧。

**Comment by daize1994** [comment]
请问怎么使用呢？README没有介绍详细的使用方法

**Comment by godcong** [comment]
> 请问怎么使用呢？README没有介绍详细的使用方法
v3还没好,所以没有readme.
现在还在写周易算法.

一定要用的话就先使用,v2版本吧.
v2版本有v2版本的readme.

**Comment by gznovice** [comment]
你好，我是这么做的。

创建了main.go，但是输出一堆东西，200多K，不知道是什么。

可能是我调用出了问题，请赐教，谢谢。

**Comment by gznovice** [comment]
package main
import (
	_ "github.com/godcong/fate/config"
	"github.com/godcong/fate"
	_ "github.com/godcong/fate/model"	
)
func main() {
    fate.FilterBest(fate.NewName("钟国仁"))
}

**Comment by godcong** [comment]
就是一堆东西，所以才要开发第三版。
第二版是按照三才五格把符合规则的都输出了。
第二字+第三字 这样一套一组




jumbycc@163.com
 
发件人： gznovice
发送时间： 2018-12-05 17:29
收件人： godcong/fate
抄送： godcong; State change
主题： Re: [godcong/fate] 怎么把这个项目运行起来。 (#4)
package main
import (
_ "github.com/godcong/fate/config"
"github.com/godcong/fate"
_ "github.com/godcong/fate/model"
)
func main() {
fate.FilterBest(fate.NewName("钟国仁"))
}

**Comment by gznovice** [comment]
很有兴趣第三版，有无机会合作啊？联系zhiqiang_z@163.com，谢谢

**Comment by zhang-victor** [comment]
我正在尝试运行这个项目，但是v3.5.3下，运行create_name_example，貌似是mysql数据库关键字character触发问题，导致sql无法执行。 @godcong  能否指导一下如何解决这个问题。

![image](https://user-images.githubusercontent.com/8773203/119436620-135f2280-bd4f-11eb-98cd-78ce6fee72dd.png)

**Comment by godcong** [comment]
> 我正在尝试运行这个项目，但是v3.5.3下，运行create_name_example，貌似是mysql数据库关键字character触发问题，导致sql无法执行。 @godcong 能否指导一下如何解决这个问题。
> 
> ![image](https://user-images.githubusercontent.com/8773203/119436620-135f2280-bd4f-11eb-98cd-78ce6fee72dd.png)

后面要加参数，不然无法运行。像这样：
```
go run main.go name -l 张 -b "2020/02/06 15:04"
```
或者直接使用二进制文件跑，也要带上参数的
