### ISSUE TITLE
window环境下config.json修改了还是报错？

### ISSUE THREAD

**Issue by ziyekudeng** [godcong/fate#41]
1.数据库已导入
2.连接正常
3.config已正常修改
C:\Users\Administrator\Downloads\fate_win64>fate.exe name -l 张 -b "2020/02/06 15:04"
config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:123456 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1583323193.947692,"caller":"fate/fate.go:133","msg":"正在使用Fate生 成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1583323193.9486935,"caller":"console/name.go:34","msg":"makename","error":"count total error:The system cannot find the path specified.","stacktrace":"github.com/goextension/log.Fatalw\n\tD:/workspace/golang/path/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/workspace/golang/project/fate/cmd/console/name.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/workspace/golang/project/fate/cmd/console/main.go:21\nruntime.main\n\tD:/workspace/golang/go_base/go1.13.1/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
那应该是和这个同样的问题：github.com/godcong/fate/issues/39
可以下载zoneinfo.zip到GOROOT对应目录下
或者安装一下GO

**Comment by naivecao** [comment]
白搭了，实在玩不转了。等你的网页版

**Comment by YuTingLiu** [comment]
不安装GO，zoneif.zip放到什么位置 @naivecao

**Comment by naivecao** [comment]
我压根就没配起来。不安装go，论说只是用fate.exe也是可以的，都打包好了

在 2020-03-09 09:17:54，YuTing <notifications@github.com> 写道：


不安装GO，zoneif.zip放到什么位置 @naivecao

**Comment by godcong** [comment]
GOROOT可以自己定义全局环境变量
或者放到默认的$HOME的go/lib/time下

**Comment by YuTingLiu** [comment]
go env有正常输出，GOROOT也可以看到，zip文件已经复制。仍然显示上述问题。
数据库日志看到没有访问。

**Comment by YuTingLiu** [comment]
源码cmd/console下编译可以正常执行了，很奇怪。
的确会输出大量生僻字，我觉得把这些字删除其实就可以了

**Comment by godcong** [comment]
> 源码cmd/console下编译可以正常执行了，很奇怪。
> 的确会输出大量生僻字，我觉得把这些字删除其实就可以了
嗯,这些都是字库里的字,优化这个挺花时间的,只能慢慢来.

**Comment by naivecao** [comment]
我用虚拟机搭了一个Ubuntu，一切正常。试了一下生成的name.txt 有3.3G。



在 2020-03-12 13:27:15，"godcong is not god" <notifications@github.com> 写道：

源码cmd/console下编译可以正常执行了，很奇怪。
的确会输出大量生僻字，我觉得把这些字删除其实就可以了
嗯,这些都是字库里的字,优化这个挺花时间的,只能慢慢来.

**Comment by godcong** [comment]
> 我用虚拟机搭了一个Ubuntu，一切正常。试了一下生成的name.txt 有3.3G。 在 2020-03-12 13:27:15，"godcong is not god" <notifications@github.com> 写道： 源码cmd/console下编译可以正常执行了，很奇怪。 的确会输出大量生僻字，我觉得把这些字删除其实就可以了 嗯,这些都是字库里的字,优化这个挺花时间的,只能慢慢来. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or unsubscribe.

这容量有点异常，虽然还是很大，应该在200M左右的。

**Comment by telami** [comment]
吐了，就不能好好完善一下文档么

**Comment by godcong** [comment]
数据已改为常用汉字库:
https://github.com/godcong/fate/releases/tag/v3.5.1

**Comment by asuralove** [comment]
你好,我按照例子输入 fate.exe name -l 张 -b "2020/02/06 15:04" 提示 malformed time zone information
