### ISSUE TITLE
{"level":"fatal","ts":1583673730.8704226,"caller":"console/name.go:34","msg":"makename","error":"count total error:The system cannot find the path 

### ISSUE THREAD

**Issue by naivecao** [godcong/fate#42]
哥们，帮忙看一下这个错误。我是数据库也配上了 go也安装了，就是不行，非科班的，麻烦了

config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:111111 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1583673730.8694227,"caller":"fate/fate.go:133","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1583673730.8704226,"caller":"console/name.go:34","msg":"makename","error":"count total error:The system cannot find the path specified.","stacktrace":"github.com/goextension/log.Fatalw\n\tD:/workspace/golang/path/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/workspace/golang/project/fate/cmd/console/name.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/workspace/golang/project/fate/cmd/console/main.go:21\nruntime.main\n\tD:/workspace/golang/go_base/go1.13.1/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
参考：https://github.com/godcong/fate/issues/41
