### ISSUE TITLE
初学者学习代码

### ISSUE THREAD

**Issue by songjian0270** [godcong/fate#45]
func (xy *XiYong) AddFen(s string, point int) {
	if xy.WuXingFen == nil {
		xy.WuXingFen = make(map[string]int)
	}

	if v, b := xy.WuXingFen[s]; b {
		xy.WuXingFen[s] = v + point
	} else {
		xy.WuXingFen[s] = point
	}
}

if v, b := xy.WuXingFen[s]; b   此处赋值之后是判断b是否为true?还是什么意思呢 大神.

**Comment by godcong** [comment]
map的第二参数判断这个key存在不存在,存在为true,不存在为false
;后面的b是判断
go可以把赋值和判断写在一行里面.

ps:别拿我的的学啊,没啥好学的,写得不好...最近老想整改着呢...

**Comment by songjian0270** [comment]
先学基础的东西，看看能不能改成java的

**Comment by songjian0270** [comment]
在提示bazi_test.go的时候go get 不了github.com/godcong/fate

**Comment by design365** [comment]
> map的第二参数判断这个key存在不存在,存在为true,不存在为false
> ;后面的b是判断
> go可以把赋值和判断写在一行里面.
> 
> ps:别拿我的的学啊,没啥好学的,写得不好...最近老想整改着呢...

把生僻字去掉，就好了

**Comment by godcong** [comment]
数据使用常用汉字表:
https://github.com/godcong/fate/releases/tag/v3.5.1
