### ISSUE TITLE
能否参考微信小程序“起名研究所”的名字算法优化下候选名字

### ISSUE THREAD

**Issue by comeby** [godcong/fate#49]
目前出来的名字很多读起来都不通顺，还有生僻词，选起来很费劲，可否参考下其他家的程序改进下。
这块我试了不少软件，“起名研究所”这个微信小程序是我目前发现的名字质量最高的软件，作者看能否参考改进下~

**Comment by godcong** [comment]
你是不是没用最新的库?
https://github.com/godcong/fate/releases/download/v3.5.1/fate_db_200331.7z
或者你跑一次regular也行,已经去掉生僻字了
