### ISSUE TITLE
你的第四版计划，通过AI,大数据匹配算法，已经有想法了吗？

### ISSUE THREAD

**Issue by haojie5** [godcong/fate#5]
从哪儿来的大数据呢？

**Comment by godcong** [comment]
现在是准备通过以下几个点:
名字的使用率及好坏,字的寓意,好坏,使用率,字的当前流行程度
等各方面来综合判定一个名字的好.
再经过筛选推荐.
后面流程会变成,机选,ai筛选,人选这3个步骤.

**Comment by godcong** [comment]
no new questions more than one month
