### ISSUE TITLE
我觉得就别开发图形界面和接口了，先让姓名出来的都是正常字的。

### ISSUE THREAD

**Issue by design365** [godcong/fate#50]
看了老大的计划，感觉现在最重要的是怎么能让出来的名字都是正常字，现在出来太乱了，基本没法用，并且太多了 ，其实出来100来个正常名字就可以了，这样我们也好选一个。谢谢。

**Comment by godcong** [comment]
你用最新的库了吗?
现在用的都是常用汉字

**Comment by design365** [comment]
@godcong 谢谢，看到了， 新发布的。现在就用一下。
