### ISSUE TITLE
出来的名字，用起名网站打分很低，不知道为什么。

### ISSUE THREAD

**Issue by design365** [godcong/fate#51]
按照demo运行后 ，name.txt中名字试了一下，在第三方姓名打分网站分数比较低，看下是算法上问题吗。谢谢作者
<img width="704" alt="image" src="https://user-images.githubusercontent.com/3348948/79040810-cfc65980-7c1d-11ea-86a4-0a29c0b747b8.png">

**Comment by godcong** [comment]
![image](https://user-images.githubusercontent.com/2727298/79042220-4b2d0880-7c28-11ea-9676-772c14211a73.png)

这个网站的问题吧。
我测了下这个名字还可以啊。
就生肖有点低，因为FATE只会帮你过滤忌字，但不会帮你选宜的字。

**Comment by design365** [comment]
@godcong 你这个是哪个网站参考的？

**Comment by godcong** [comment]
meimingteng
@design365
