### ISSUE TITLE
能否增加编译指导说明？

### ISSUE THREAD

**Issue by huamg12** [godcong/fate#52]
1. 建议增加编译指导说明，或者自动化编译的说明，方便入门者使用。

2. 使用release之后的fate.exe 产生如下问题：

config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:111111 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1586749217.8032405,"caller":"fate/fate.go:146","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1586749217.8042421,"caller":"console/name.go:34","msg":"makename","error":"count total error:unknown time zone Asia/Shanghai","stacktrace":"github.com/goextension/log.Fatalw\n\tC:/Users/runneradmin/go/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/a/fate/fate/cmd/console/name.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\tC:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tC:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tC:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/a/fate/fate/cmd/console/main.go:21\nruntime.main\n\tC:/hostedtoolcache/windows/go/1.13.10/x64/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
https://github.com/godcong/fate/blob/master/zoneinfo.zip
下这个和二进制文件放一起,这个readme有写
好多人没仔细看,我改下加粗下...
