### ISSUE TITLE
求助（这个怎么解决）

### ISSUE THREAD

**Issue by hzh1105** [godcong/fate#55]
![1](https://user-images.githubusercontent.com/30227363/80075819-d8078880-857d-11ea-9fb3-d9c0c5d491e2.jpg)

start 2020-04-23 16:14:08.3226558 +0800 CST m=+0.117931001
config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:1105 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1587629648.3296561,"caller":"fate/fate.go:146","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1587629648.3306522,"caller":"console/name.go:35","msg":"makename","error":"count total error:The system cannot find the path specified.","stacktrace":"github.com/goextension/log.Fatalw\n\tC:/Users/runneradmin/go/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/a/fate/fate/cmd/console/name.go:35\ngithub.com/spf13/cobra.(*Command).execute\n\tC:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tC:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tC:/Users/runneradmin/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/a/fate/fate/cmd/console/main.go:21\nruntime.main\n\tC:/hostedtoolcache/windows/go/1.13.10/x64/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
使用二进制文件在运行前务必把zoninfo.zip下载并和二进制文件放在一起,不然会报错.
The system cannot find the path一般都是找不到zoneinfo文件无法导致无法解析日期.

下载主页的zoneinfo的链接,重新init一下就行了

**Comment by hzh1105** [comment]
![1 (2)](https://user-images.githubusercontent.com/30227363/80077386-00908200-8580-11ea-844f-906187309977.jpg)
zoninfo.zip和二进制文件在一起，要不要解压

**Comment by hzh1105** [comment]
已成功，多谢

**Comment by canjian215215** [comment]
> 已成功，多谢

怎么解决的？我的和你遇到一样错误？
