### ISSUE TITLE
Can't generate a name in future time

### ISSUE THREAD

**Issue by festum** [godcong/fate#58]
Will generate an empty log file.

**Comment by godcong** [comment]
Please tell more information to find the problem.
1. Your System:  windows/linux/macos?
2. Database: mysql version and fate_db version
3. Source: source release version or commit hash or bin version

Describe the bug,what outputs?

**Comment by festum** [comment]
- Go v1.14 on Ubuntu 20.04
- MySQL 8  20/03/31
- 7be701

The only out put I can see is the help content. 

Output log remains empty, it's kinda works on the default value. Yet never working on future date like 2020/07/01 18:00

**Comment by godcong** [comment]
did you see a file named like "name.log" under your run directory?

```
cfg.FileOutput = config.FileOutput{
		OutputMode: config.OutputModeLog,
		Path:       "name.log",
	}
```
config can set output file name
