### ISSUE TITLE
[简化需求]怎么用的？

### ISSUE THREAD

**Issue by XIAOWU168** [godcong/fate#59]
一打开就显示这个
http://ww1.sinaimg.cn/large/006xqDjdgy1geog7rfjafj30xz0hraa4.jpg

**Comment by godcong** [comment]
https://github.com/godcong/fate/blob/master/README.md#%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90%E5%A7%93%E5%90%8D

**Comment by XIAOWU168** [comment]
> [https://github.com/godcong/fate/blob/master/README.md#%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6 ％E7％94％9F％E6％88％90％E5％A7％93％E5％90％8D](https://github.com/godcong/fate/blob/master/README.md#%E5%8F%AF%E6%89%A7%E8%A1%8C%E6%96%87%E4%BB%B6%E7%94%9F%E6%88%90%E5%A7%93%E5%90%8D)

还是不行，我太傻了
http://tu.yaohuo.me/imgs/2020/05/54f208084a397338.png

**Comment by godcong** [comment]
1. 安装mysql
2. 下载fate_data解压缩.
3. 然后导入sql文件(不会请参考:https://www.cnblogs.com/yuwensong/p/3955834.html)
4. 下载最新fate压缩文件解压缩.
5. 下载zoneinfo.zip和fate解压后的文件放一起.
6. 运行 `fate init`、(fate 是你解压后的文件名称)
7. 运行 `fate.exe name -l 张 -b "2020/02/06 15:04"` 生成名称.
8. 结束后运行目录下会有一个新的文件. 打开就行了

**Comment by XIAOWU168** [comment]
看来不是给普通人用的，太难搞了
![image](https://user-images.githubusercontent.com/41268642/81775287-2249ad00-951f-11ea-9321-b8b5ded01490.png)

**Comment by godcong** [comment]
这些如果你都不会的话可能暂时你就用不了...
后面会使用github的actions做一个自动化版本...这个计划优先级还比较低...

**Comment by lxw0109** [comment]
> 1. 安装mysql(用户密码设置成root/111111)
> 2. 下载fate_data解压缩.
> 3. 然后导入sql文件(不会请参考:https://www.cnblogs.com/yuwensong/p/3955834.html)
> 4. 下载最新fate压缩文件解压缩.
> 5. 下载zoneinfo.zip和fate解压后的文件放一起.
> 6. 运行 `fate init`、(fate 是你解压后的文件名称)
> 7. 运行 `fate.exe name -l 张 -b "2020/02/06 15:04"` 生成名称.
> 8. 结束后运行目录下会有一个新的文件. 用文本编辑器打开就行了

导入sql文件，sql文件在哪里？

**Comment by lxw0109** [comment]
> 1. 安装mysql(用户密码设置成root/111111)
> 2. 下载fate_data解压缩.
> 3. 然后导入sql文件(不会请参考:https://www.cnblogs.com/yuwensong/p/3955834.html)
> 4. 下载最新fate压缩文件解压缩.
> 5. 下载zoneinfo.zip和fate解压后的文件放一起.
> 6. 运行 `fate init`、(fate 是你解压后的文件名称)
> 7. 运行 `fate.exe name -l 张 -b "2020/02/06 15:04"` 生成名称.
> 8. 结束后运行目录下会有一个新的文件. 用文本编辑器打开就行了

虽然很麻烦，但是确实可用~

**Comment by tblx** [comment]
回答都那么详细太赞了。 作者开个打赏吧

**Comment by ipfans** [comment]
为什么会需要数据库。。。。

**Comment by godcong** [comment]
> 为什么会需要数据库。。。。

不用数据库我字从哪里来啊...
包括规则的预生成都存在数据库里，不然你得跑3天多

**Comment by elvisw** [comment]
感觉mysql太重了，能不能用SQLite，这样就不用安装数据库系统了

**Comment by godcong** [comment]
> 感觉mysql太重了，能不能用SQLite，这样就不用安装数据库系统了

以前有sqlite,但是编译sqlite会用到c,很多人不会编译,所以去掉了.
现在自动编译了,后面可能会考虑加上.

**Comment by zzhzero** [comment]
结果里面加个筛选吧,搞个黑名单,有些字明显不能作为名字的,还有性别这个维度也要考虑.

**Comment by frederik001** [comment]
首先感谢大神的项目！
在导入数据库的时候遇到速度慢的坑，为了方便后来人，请参考此文优化数据库设置
https://dba.stackexchange.com/questions/83125/mysql-any-way-to-import-a-huge-32-gb-sql-dump-faster

**Comment by godcong** [comment]
> 首先感谢大神的项目！
> 在导入数据库的时候遇到速度慢的坑，为了方便后来人，请参考此文优化数据库设置
> https://dba.stackexchange.com/questions/83125/mysql-any-way-to-import-a-huge-32-gb-sql-dump-faster

数据是挺多的，可以用Navicat，我用这个导入挺快的。

**Comment by frederik001** [comment]
> 
> 
> > 首先感谢大神的项目！
> > 在导入数据库的时候遇到速度慢的坑，为了方便后来人，请参考此文优化数据库设置
> > https://dba.stackexchange.com/questions/83125/mysql-any-way-to-import-a-huge-32-gb-sql-dump-faster
> 
> 数据是挺多的，可以用Navicat，我用这个导入挺快的。

Navicat果然高效……分分钟搞定，谢谢大神！

**Comment by ZhuTail** [comment]
sql文件在哪...

**Comment by jiayaoO3O** [comment]
我有一个建议,直接将项目部署在github action 然后想要取名字的用户只需要在issues提一个issue或者评论,写上姓氏,生日等参数,这个时候自动触发action,算出的结果再用action的回复功能回复给这个用户即可.

**Comment by ankye** [comment]
我生成了20w条记录，怎么才能找到想要的名字，这个数量还是太大了

**Comment by godcong** [comment]
add requirements into #21

**Comment by BaiGeorge** [comment]
> 下载zoneinfo.zip和fate解压后的文件放一

大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。

先谢过！

![image](https://user-images.githubusercontent.com/63640888/94361765-6c57b780-00e9-11eb-9930-3ed67090a7c5.png)
![image](https://user-images.githubusercontent.com/63640888/94361778-78dc1000-00e9-11eb-9d13-34d817c896ba.png)
![image](https://user-images.githubusercontent.com/63640888/94361802-a1fca080-00e9-11eb-81e0-97ba1079d5a4.png)

**Comment by godcong** [comment]
> > 下载zoneinfo.zip和fate解压后的文件放一
> 
> 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> 
> 先谢过！
> 
> ![image](https://user-images.githubusercontent.com/63640888/94361765-6c57b780-00e9-11eb-9930-3ed67090a7c5.png)
> ![image](https://user-images.githubusercontent.com/63640888/94361778-78dc1000-00e9-11eb-9d13-34d817c896ba.png)
> ![image](https://user-images.githubusercontent.com/63640888/94361802-a1fca080-00e9-11eb-81e0-97ba1079d5a4.png)

你下载auto_build版本试一下
zoneinfo的bug 3.5.1以后才修正的...

**Comment by BaiGeorge** [comment]
> 下载zoneinfo.zip和fate解压后的文件放一
> 
> 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> 先谢过！
> 
> 你下载auto_build版本试一下
> zoneinfo的bug 3.5.1以后才修正的...

多谢大神！试了一下好像可以了，不过有3GB的txt文件，打都打不开，是不是我config有啥问题

**Comment by godcong** [comment]
> > 下载zoneinfo.zip和fate解压后的文件放一
> > 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> > 先谢过！
> > 你下载auto_build版本试一下
> > zoneinfo的bug 3.5.1以后才修正的...
> 
> 多谢大神！试了一下好像可以了，不过有3GB的txt文件，打都打不开，是不是我config有啥问题

你数据库用的是哪个?
https://github.com/godcong/fate/releases/download/v3.5.1/fate_db_200331.7z
这个是常用汉字.
以前的库是所有汉字,有区别的.

**Comment by BaiGeorge** [comment]
> 下载zoneinfo.zip和fate解压后的文件放一
> 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> 先谢过！
> 你下载auto_build版本试一下
> zoneinfo的bug 3.5.1以后才修正的...
> 
> 多谢大神！试了一下好像可以了，不过有3GB的txt文件，打都打不开，是不是我config有啥问题
> 
> 你数据库用的是哪个?
> https://github.com/godcong/fate/releases/download/v3.5.1/fate_db_200331.7z
> 这个是常用汉字.
> 以前的库是所有汉字,有区别的.

我用的是下面这个页面的fate0206.7z
https://github.com/godcong/fate/releases/tag/v3.1.1

那换了常用汉字的数据库是不是重新导入MySQL，然后就可以跑了？config文件要相应修改吗？

谢谢大神！

**Comment by godcong** [comment]
> > 下载zoneinfo.zip和fate解压后的文件放一
> > 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> > 先谢过！
> > 你下载auto_build版本试一下
> > zoneinfo的bug 3.5.1以后才修正的...
> > 多谢大神！试了一下好像可以了，不过有3GB的txt文件，打都打不开，是不是我config有啥问题
> > 你数据库用的是哪个?
> > https://github.com/godcong/fate/releases/download/v3.5.1/fate_db_200331.7z
> > 这个是常用汉字.
> > 以前的库是所有汉字,有区别的.
> 
> 我用的是下面这个页面的fate0206.7z
> https://github.com/godcong/fate/releases/tag/v3.1.1
> 
> 那换了常用汉字的数据库是不是重新导入MySQL，然后就可以跑了？config文件要相应修改吗？
> 
> 谢谢大神！

对,把原来的数据都删了,重新导入一遍就可以直接跑了.　
别的都不用动.
生成的名字应该会缩减到只有几千个了

**Comment by BaiGeorge** [comment]
> 下载zoneinfo.zip和fate解压后的文件放一
> 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> 先谢过！
> 你下载auto_build版本试一下
> zoneinfo的bug 3.5.1以后才修正的...
> 多谢大神！试了一下好像可以了，不过有3GB的txt文件，打都打不开，是不是我config有啥问题
> 你数据库用的是哪个?
> https://github.com/godcong/fate/releases/download/v3.5.1/fate_db_200331.7z
> 这个是常用汉字.
> 以前的库是所有汉字,有区别的.
> 
> 我用的是下面这个页面的fate0206.7z
> https://github.com/godcong/fate/releases/tag/v3.1.1
> 那换了常用汉字的数据库是不是重新导入MySQL，然后就可以跑了？config文件要相应修改吗？
> 谢谢大神！
> 
> 对,把原来的数据都删了,重新导入一遍就可以直接跑了.　
> 别的都不用动.
> 生成的名字应该会缩减到只有几千个了

多谢解答！换了数据库之后运行exe文件快了很多，出来的txt也只有几十mb的大小，但不知道为啥还是有几十万个名字。
还有就是，算法是穷举了所有可能的笔画数组合吗？还是对笔画数有筛选？貌似很多人取名字是根据笔画数打分来的。
对了，我还发现了下面这个，貌似笔画数不太对？
![image](https://user-images.githubusercontent.com/63640888/94465506-95b03a80-01f2-11eb-9de7-36a078d0b057.png)
谢谢！

**Comment by godcong** [comment]
> > 下载zoneinfo.zip和fate解压后的文件放一
> > 大神，还是不太行啊，能不能帮忙看下原因？还是说system cannot find the path specified。感觉像是“下载zoneinfo.zip和fate解压后的文件放一起”这条没做对，但下面第二个截图显示也是没问题的啊。。。
> > 先谢过！
> > 你下载auto_build版本试一下
> > zoneinfo的bug 3.5.1以后才修正的...
> > 多谢大神！试了一下好像可以了，不过有3GB的txt文件，打都打不开，是不是我config有啥问题
> > 你数据库用的是哪个?
> > https://github.com/godcong/fate/releases/download/v3.5.1/fate_db_200331.7z
> > 这个是常用汉字.
> > 以前的库是所有汉字,有区别的.
> > 我用的是下面这个页面的fate0206.7z
> > https://github.com/godcong/fate/releases/tag/v3.1.1
> > 那换了常用汉字的数据库是不是重新导入MySQL，然后就可以跑了？config文件要相应修改吗？
> > 谢谢大神！
> > 对,把原来的数据都删了,重新导入一遍就可以直接跑了.　
> > 别的都不用动.
> > 生成的名字应该会缩减到只有几千个了
> 
> 多谢解答！换了数据库之后运行exe文件快了很多，出来的txt也只有几十mb的大小，但不知道为啥还是有几十万个名字。
> 还有就是，算法是穷举了所有可能的笔画数组合吗？还是对笔画数有筛选？貌似很多人取名字是根据笔画数打分来的。
> 对了，我还发现了下面这个，貌似笔画数不太对？
> ![image](https://user-images.githubusercontent.com/63640888/94465506-95b03a80-01f2-11eb-9de7-36a078d0b057.png)
> 谢谢！

是先过滤出最佳笔画组合,然后穷举所有符合笔画数的字
然后再过滤其他规则
