### ISSUE TITLE
比较关心能不能通过输入姓氏，生辰计算一批姓名，并标注得分？

### ISSUE THREAD

**Issue by bugstark** [godcong/fate#6]
感谢开源，膜拜

**Comment by godcong** [comment]
目标就是这样的,
但是优先生成得分高的,
毕竟起名你得分低的名字拿去也没啥用.
对吧?

**Comment by bugstark** [comment]
可以order by更好吧，长度，得分等偏好进行排序。我看现在的大部分起名都是做的数据采集，用户查询的时候进行匹配。

**Comment by godcong** [comment]
这种你敢用吗?提前生成一批,不管你生辰八字,生肖五行...pia...就给你一坨...

**Comment by godcong** [comment]
no new questions more than one month
