### ISSUE TITLE
运行报错 count total error:The system cannot find the path specified.

### ISSUE THREAD

**Issue by bluesheepcj** [godcong/fate#60]
windows 10 环境
系统自带PowerShell
没有go语言环境，exe文件运行，文件夹下有文件：
fate.exe
config.json
zoneinfo.zip

数据库为mysql，数据已导入，一共100多万
数据库密码也已经配置在config中了
运行命令：
.\fate.exe name -l 杨 -b "2020/05/14 08:30"

请帮忙看下我哪里有问题
报错信息：
config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:123456 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1589614328.0149333,"caller":"fate/fate.go:133","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1589614328.0199234,"caller":"console/name.go:34","msg":"makename","error":"count total error:The system cannot find the path specified.","stacktrace":"github.com/goextension/log.Fatalw\n\tD:/workspace/golang/path/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/workspace/golang/project/fate/cmd/console/name.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/workspace/golang/project/fate/cmd/console/main.go:21\nruntime.main\n\tD:/workspace/golang/go_base/go1.13.1/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
还是zoneinfo的问题。
是不是init失败了。
你下载最新auto_build版本试试：version: 3944c19
我加了一些日志，还有zoneinfo的一些检查。
只要根目录下有zoneinfo就不会出问题了。

**Comment by peiguojie123** [comment]
我也遇到同样的问题，

**Comment by godcong** [comment]
> @godcong 我也是楼上同样的问题，我安装go语言环境也试了，还是同样的报错，各位兄弟有解决办法吗？

是最新版吗?
