### ISSUE TITLE
运行的时候报错，zoneinfo file is not exist

### ISSUE THREAD

**Issue by honeylucky** [godcong/fate#67]
{"level":"fatal","ts":1592981709.3021247,"caller":"console/name.go:27","msg":"zoneinfo file is not exist","error":"stat zoneinfo.zip: no such file or directory

**Comment by godcong** [comment]
请看Q1:
下载master下的zoneinfo.zip,放一起

**Comment by honeylucky** [comment]
谢谢，接下来还抱这个错
Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path: Heads:[]}}panic: couldn't open sink "": open : no such file or directory

**Comment by honeylucky** [comment]
@godcong

**Comment by godcong** [comment]
我这没找到有这个panic内容输出的地方，能把具体点的日志发上来吗？
panic一般会打印好几行出错的，应该会把整个调用顺序都输出来的。

**Comment by honeylucky** [comment]
xc0000a2c80, 0xc00006b680, 0x4, 0x4, 0xc0000a2c80, 0xc00006b680)
        /home/runner/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xe108a0, 0xc0000c1f40, 0x2, 0x2)
        /home/runner/go/pkg/mod/github.com/spf1

**Comment by godcong** [comment]
你把config那个文件删了,重新init一遍.
不知道你的config配置改了什么,但是从错误内容上来看是找不到文件输出的位置了.
