### ISSUE TITLE
请问常用字库怎么自定义？

### ISSUE THREAD

**Issue by honeylucky** [godcong/fate#70]
@godcong 
我想添加自己定义的常用字，这个如何加进去？这样能保证出来的名字都是自己定义的常见字库

**Comment by honeylucky** [comment]
我发现即使把character表里的所有记录的regular 字段设置为0， 然后修改自己认为常用字的regular字段设置为1，起名的时候根本没根据这个来。很奇怪啊。

**Comment by honeylucky** [comment]
强烈建议最着急的是打分算法，出来这么多姓名，没法筛选啊，别的功能都不用做，主要就是这个打分功能最重要也是最紧急，出来的结果按照打分从高到低排序。这才是这个项目最有用的功能。谢谢。

**Comment by godcong** [comment]
> @godcong
> 我想添加自己定义的常用字，这个如何加进去？这样能保证出来的名字都是自己定义的常见字库

常用字用的是中华人民共和国常用字库。
如果你要改的话sql的character表，Regular全部设置成false，然后把你自己要用的设置成true。（这样就没有常用字了，只会从你选的字选了）

**Comment by godcong** [comment]
输出的名字都是最符合规则的名字。
所以理论上这些名字的分值基本上都是一样的。所以现在上这个没有什么必要。

所以你说的这个可能要和自定义功能一起搞
