### ISSUE TITLE
[BUG]count total error:dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by renchuanrc** [godcong/fate#73]
**Describe the bug**
config loaded: &{RunInit:false FilterMode:0 StrokeMax:18 StrokeMin:3 HardFilter:false FixBazi:false SupplyFilter:true ZodiacFilter:true BaguaFilter:true Regular:true Database:{Host:127.0.0.1 Port:3306 User:root Pwd:111111 Name:fate MaxIdleCon:0 MaxOpenCon:0 Driver:mysql File: Dsn: ShowSQL:false ShowExecTime:false} FileOutput:{OutputMode:0 Path:name.txt Heads:[姓名 笔画 拼音 喜用神 八字]}}{"level":"info","ts":1594343424.084123,"caller":"fate/fate.go:133","msg":"正在使用Fate生 成姓名列表，如遇到问题请访问项目地址：https://github.com/godcong/fate获取帮助!"}
{"level":"fatal","ts":1594343426.1276681,"caller":"console/name.go:34","msg":"makename","error":"count total error:dial tcp 127.0.0.1:3306: connectex: No connection could be made because the target machine actively refused it.","stacktrace":"github.com/goextension/log.Fatalw\n\tD:/workspace/golang/path/pkg/mod/github.com/goextension/log@v0.0.2/log.go:128\nmain.cmdName.func1\n\tD:/workspace/golang/project/fate/cmd/console/name.go:34\ngithub.com/spf13/cobra.(*Command).execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830\ngithub.com/spf13/cobra.(*Command).ExecuteC\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914\ngithub.com/spf13/cobra.(*Command).Execute\n\tD:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864\nmain.main\n\tD:/workspace/golang/project/fate/cmd/console/main.go:21\nruntime.main\n\tD:/workspace/golang/go_base/go1.13.1/src/runtime/proc.go:203"}

**Comment by godcong** [comment]
1. do you installed a mysql server and dump the lastest data into the mysql ?
2. if your mysql login username and password is not `User:root Pwd:111111`, you need change it.

**Comment by godcong** [comment]
Hello, has your problem been solved?
If not, please submit a more detailed problem report.
If solved, I will close this issue.

**Comment by godcong** [comment]
I closed this issue.
If you still have problems, you can reopen it.
