### ISSUE TITLE
输出字段只包含目前默认输出的吗

### ISSUE THREAD

**Issue by anbo724** [godcong/fate#74]
你好，我看到输出的格式为：
“{"name":"张之检","笔画":"11,4,17","拼音":"[zhàng,zhāng][zhī][jiǎn]","喜用神":"火","八字":"庚子戊寅己卯壬申"}”
但是我看介绍里面还包含：周易卦象  
大衍之数  
三才五格  
喜用神（平衡用神）  
生肖用字  
八字吉凶  
怎么能得到这些信息呢？我在config文件里面增加了一个字段“周易卦象 ”输出的结果是没有变化的。
求指导！

**Comment by godcong** [comment]
字段输出没加,仅用来过滤了

**Comment by anbo724** [comment]
好的谢谢，不过感觉如果能输出这些信息会更有参考价值。

**Comment by godcong** [comment]
add requrements into #21
