### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by renchuanrc** [godcong/fate#75]
**Describe the bug**
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x38 pc=0x8a1dec]

goroutine 1 [running]:
github.com/godcong/fate.(*Zodiac).zodiacJi(...)
        D:/workspace/golang/project/fate/zodiac.go:48
github.com/godcong/fate.(*Zodiac).Point(0x0, 0xc00036e500, 0x0)
        D:/workspace/golang/project/fate/zodiac.go:71 +0x6c
github.com/godcong/fate.(*Zodiac).PointCheck(0x0, 0x3, 0xc000370040, 0x2, 0x2, 0x1)
        D:/workspace/golang/project/fate/zodiac.go:61 +0x5e
github.com/godcong/fate.filterZodiac(0xa8d8e0, 0xc0001dc080, 0xc000370040, 0x2, 0x2, 0x1)
        D:/workspace/golang/project/fate/zodiac.go:55 +0x71
github.com/godcong/fate.(*fateImpl).MakeName(0xc0000b2840, 0xa8f660, 0xc000020150, 0xeca5bd58c, 0x0)
        D:/workspace/golang/project/fate/fate.go:177 +0x16dd
main.cmdName.func1(0xc000091400, 0xc00005b780, 0x0, 0x4)
        D:/workspace/golang/project/fate/cmd/console/name.go:32 +0x300
github.com/spf13/cobra.(*Command).execute(0xc000091400, 0xc00005b700, 0x4, 0x4, 0xc000091400, 0xc00005b700)
        D:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2b1
github.com/spf13/cobra.(*Command).ExecuteC(0xdf03a0, 0xc00008ff40, 0x2, 0x2)
        D:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x302
github.com/spf13/cobra.(*Command).Execute(...)
        D:/workspace/golang/path/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        D:/workspace/golang/project/fate/cmd/console/main.go:21 +0x92

**Environment**
System:  win10
Database: mysql 8

**Comment by godcong** [comment]
which version did you used?
the older version always panic, when your zodiac is out of  "猪"，“鼠”，“牛”

**Comment by godcong** [comment]
Hello, has your problem been solved?
If not, please submit a more detailed problem report.
Otherwise I will close this Issue.

**Comment by godcong** [comment]
I closed this issue.
If you still have problems, you can reopen it.
