### ISSUE TITLE
刚性需求清单

### ISSUE THREAD

**Issue by Z-fly** [godcong/fate#77]
各位列一下刚性需求吧。
我先来

1.黑白名单
黑名单：此参数用来在最后输出时忽略掉指定汉字
白名单：此参数用来在最后输出时优先输出指定汉字

2.程序封装
封装成 GUI/WEB/API
封装至Docker

**Comment by godcong** [comment]
能1234一条一条标记下吗?　:)

**Comment by Z-fly** [comment]
> 能1234一条一条标记下吗?　:)

已经标记。

**Comment by godcong** [comment]
update into: #21 21

**Comment by niuxiongwen** [comment]
3、名字打分

**Comment by godcong** [comment]
@niuxiongwen added into https://github.com/babyname/fate/issues/21 7
