### ISSUE TITLE
[问题]张妖死 这种名字都有，我是不是没弄好啊

### ISSUE THREAD

**Issue by flashrick** [godcong/fate#78]
born := chronos.New("2020/01/14 02:45")
	//姓氏
	lastName := "张"
	cfg := config.DefaultConfig()
	cfg.BaguaFilter = true
	cfg.ZodiacFilter = true
	cfg.SupplyFilter = true
	cfg.HardFilter = true
	cfg.StrokeMin = 3
	cfg.StrokeMax = 10
	cfg.Database = config.Database{
		Host:         "localhost",
		Port:         "3306",
		User:         "root",
		Pwd:          "root",
		Name:         "fate",
		MaxIdleCon:   0,
		MaxOpenCon:   0,
		Driver:       "mysql",
		File:         "",
		Dsn:          "",
		ShowSQL:      false,
		ShowExecTime: false,
	}

**Comment by godcong** [comment]
这个有什么问题吗?
工具只会帮你过滤规则(生克八字五行周易),
不会主观地去过滤贬义褒义的字.
喜欢不喜欢,好与不好, 还要看你自己的主观意识.

好比在古代龟,狗这些都是褒义词.
放在现代就没人去用这个了.

**Comment by godcong** [comment]
这个有什么问题吗?
工具只会帮你过滤规则(生克八字五行周易),
不会主观地去过滤贬义褒义的字.
喜欢不喜欢,好与不好, 还要看你自己的主观意识.

好比在古代龟,狗这些都是褒义词.
放在现代就没人去用这个了.

**Comment by flashrick** [comment]
也是，我能配置过滤掉哪些用字吗

**Comment by godcong** [comment]
> 也是，我能配置过滤掉哪些用字吗

现在还没加这个功能.
在下一个计划当中
