### ISSUE TITLE
[BUG]无法生成名字，name文件是空的。

### ISSUE THREAD

**Issue by hyzgit** [godcong/fate#83]
数据库都弄好了，运行也没什么错误，但是最终没有生成名字。

**Comment by godcong** [comment]
能提供下生成名字的参数么？

**Comment by hyzgit** [comment]
> 能提供下屏幕输出的LOG和生成名字的参数么？

看样子是日期和时间的问题，name -l 张 -b "2020/09/29 18:10"

**Comment by hyzgit** [comment]
D:\tools\fate>fate_windows_amd64.exe name -l 张 -b "2020/09/29 15:04"
start 2020-10-07 22:32:24.7127917 +0800 CST m=+0.057979101
{"level":"info","ts":1602081144.712792,"caller":"console/name.go:41","msg":"show config info","data":{"run_init":false,"filter_mode":0,"stroke_max":18,"stroke_min":3,"hard_filter":false,"fix_bazi":false,"supply_filter":true,"zodiac_filter":true,"bagua_filter":true,"regular":true,"database":{"host":"192.168.2.196","port":"3307","user":"root","pwd":"Yzh@hyjJJ18","name":"fate","max_idle_con":0,"max_open_con":0,"driver":"mysql","file":"","dsn":"","show_sql":false,"show_exec_time":false},"file_output":{"output_mode":0,"path":"name.txt","heads":["姓名","笔画","拼音","喜用神","八字"]}}}
{"level":"info","ts":1602081144.7358372,"caller":"fate/fate.go:137","msg":"正在使用Fate生成姓名列表，如遇到问题请访问项 目地址：https://github.com/godcong/fate获取帮助!"}
end 2020-10-07 22:32:28.8999457 +0800 CST m=+4.245133101

D:\tools\fate>

**Comment by hyzgit** [comment]
直接用默认的参数，也不行

**Comment by hyzgit** [comment]
好像是日期 2020/09/29 有问题。

**Comment by godcong** [comment]
> 好像是日期 2020/09/29 有问题。
是的，五行判断的时候用了==。
把supply_filter设置成false，或者重新下一下最新的修正版本。

**Comment by hyzgit** [comment]
> > 好像是日期 2020/09/29 有问题。
> > 是的，五行判断的时候用了==。
> > 把supply_filter设置成false，或者重新下一下最新的修正版本。
新版本可以了，谢谢
