### ISSUE TITLE
太棒了，这就是我一直想做却没法做的事情

### ISSUE THREAD

**Issue by hongmaoxiao** [godcong/fate#86]
感谢开源，请问我可以用这个数据做个起名小程序吗

**Comment by godcong** [comment]
可以啊

**Comment by hongmaoxiao** [comment]
> 可以啊

多谢，另外我觉得是不是可以加入《道德经》的内容，毕竟很多人起名都是参考里面的

**Comment by godcong** [comment]
> > 可以啊
> 
> 多谢，另外我觉得是不是可以加入《道德经》的内容，毕竟很多人起名都是参考里面的

需要把所有的字打散了存成一个表就行了吧

**Comment by hongmaoxiao** [comment]
基本思路是这样
最好是能把不适合放首字的情况排除掉

**Comment by hongmaoxiao** [comment]
组合不是难事
难的是组合以后的释义
