### ISSUE TITLE
有生成name.txt ，但是数量好多？不知道有没有配置正确。

### ISSUE THREAD

**Issue by zuowanbushiwo** [godcong/fate#89]
配置如下：
{
 "run_init": false,
 "filter_mode": 0,
 "stroke_max": 18,
 "stroke_min": 3,
 "hard_filter": false,
 "fix_bazi": false,
 "supply_filter": true,
 "zodiac_filter": true,
 "bagua_filter": true,
 "regular": true,
 "database": {
  "host": "127.0.0.1",
  "port": "3306",
  "user": "root",
  "pwd": "123456",
  "name": "fate",
  "max_idle_con": 0,
  "max_open_con": 0,
  "driver": "mysql",
  "file": "",
  "dsn": "",
  "show_sql": false,
  "show_exec_time": false
 },
 "file_output": {
  "output_mode": 0,
  "path": "name.txt",
  "heads": [
   "姓名",
   "笔画",
   "拼音",
   "喜用神",
   "八字"
  ]
 }
}

使用我自己小孩的数据测试产生的29.5万个。

使用fate_windows_amd64.exe name -l 张 -b "2020/02/06 15:04" 这个测试产生的29.2万个，不知道是不是正常的？

都是用的数据库用的是fate_200331.sql，exe用的是auto build 最新的。

**Comment by godcong** [comment]
按照姓氏与出生日期的不同，生成的规则姓名，大概从几千到几万不等。如果姓氏与出生日期较好的也有可能更多点，可选范围更加广泛点。

**Comment by zuowanbushiwo** [comment]
那用最新的数据库 测试你ReadMe.txt 里面的  fate_windows_amd64.exe name -l 张 -b "2020/02/06 15:04"  这个应该是多少？会是固定的吗？我这边是29.2万个。 我怕我的sql 导入不对。因为没有用过数据库，选择的是mysql 直接导入，导入了好长的时间，第二天起来看，CMD 窗口都自动关闭了，不知道是不是完全导入成功了。如果导入错误了，用什么命令删除啊？我再用你说的软件导入一遍，谢谢！

**Comment by godcong** [comment]
sql如果不对的话应该是没有数据产生的。
sql里面的只是字库之类的数据

**Comment by zuowanbushiwo** [comment]
好的，谢谢！那你使用 fate_windows_amd64.exe name -l 张 -b "2020/02/06 15:04"  产生的name是多少？环境一样会是固定的吗？

**Comment by EdenWat** [comment]
请问 fate_200331.sql 这个文件在哪里呀

**Comment by godcong** [comment]
> 请问 fate_200331.sql 这个文件在哪里呀
请看README 【最新数据库文件:20200331】
